import os,json
from flask import Flask,Response
app=Flask(__name__)
ITEMS=['패널','보드','전원','PC','카메라','스피커','마이크','입력장치','하우징','외관데코','기타']
LOCS={'금정구':['아이숫들락날락(구.금성어린이집)','금정체육공원','금정도서관'],'기장군':['기장어린이도서관','안데르센동화마을'],'남구':['대동골문화센터'],'동구':['애니랑 들락날락'],'동래구':['온빟어린이작은도서관','혁신어울림센터','부산사회복지종합센터','부산해양자연사박물관'],'부산진구':['부산진구 기적의도서관','전포어울더울작은도서관','부산진구어린이청소년도서관','껼자람작은도서관'],'북구':['만덕종합사회복지관','시랑꿈아이누리 작은도서관','덕전도서관'],'사상구':['사상육아종합지원센터','꿈나래작은도서관','주례쌌지도서관','사상어린이도서관','그리며 들락날락','부산도서관 꿈뜨락'],'사하구':['올숙도문화회관','다대도서관','노을나루길작은도서관'],'서구':['서구문화원 작은도서관(전마니)','아동보호종합센터','한형석자유아동극장'],'수영구':['도모헌 숲속체험관','망미작은도서관'],'연제구':['부산시청','언제만화도서관'],'영도구':['풀잎작은도서관','부산복합혜신센터'],'중구':['근현대역사관'],'해운대구':['송정동 어린이작은도서관','영화의전당','반송종합사회복지관']}
@app.route('/')
def home():
    return Response(build_html(),mimetype='text/html')

def build_html():
    IT=json.dumps(ITEMS,ensure_ascii=False)
    LC=json.dumps(LOCS,ensure_ascii=False)
    H=[]
    H.append('<!DOCTYPE html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>\uBA54\uD0C0\uB3C4\uC5B4</title>')
    H.append('<style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:system-ui;display:flex;justify-content:center;align-items:flex-start;min-height:100vh;background:#e8e8e8;padding:8px}')
    H.append('#p{width:375px;height:812px;background:#fff;border-radius:40px;border:12px solid #000;overflow:hidden;display:flex;flex-direction:column;box-shadow:0 20px 60px rgba(0,0,0,.3)}')
    H.append('.n{background:#000;height:28px;display:flex;align-items:center;justify-content:center;color:#fff;font-size:8px}')
    H.append('.s{background:#000;height:24px;display:flex;justify-content:space-between;padding:0 12px;color:#fff;font-size:10px;align-items:center}')
    H.append('.pg{flex:1;display:none;flex-direction:column;overflow:hidden}.pg.sh{display:flex}')
    H.append('.lg{background:linear-gradient(135deg,#1e5a96,#154a7a);justify-content:center;align-items:center;padding:40px}')
    H.append('.cd{background:#fff;border-radius:16px;padding:32px;text-align:center}')
    H.append('.ico{font-size:48px;margin-bottom:16px}.nm{font-size:23px;font-weight:700;margin-bottom:8px;color:#222}')
    H.append('.sb{font-size:11px;color:#999;margin-bottom:24px}')
    H.append('.lbl{font-size:11px;color:#666;text-align:left;display:block;margin-bottom:4px}')
    H.append('input[type=text],input[type=password]{width:100%;padding:10px;margin-bottom:12px;border:1px solid #ddd;border-radius:8px;font-size:13px}')
    H.append('.bl{width:100%;padding:11px;background:#1e5a96;color:#fff;border:none;border-radius:8px;font-weight:600;cursor:pointer;font-size:14px}')
    H.append('.slp{flex:1;flex-direction:column;overflow:hidden}')
    H.append('.hd{background:linear-gradient(135deg,#1e5a96,#154a7a);color:#fff;padding:12px 16px}')
    H.append('.hd-title{font-size:14px;font-weight:700}.hd-sub{font-size:10px;opacity:.8;margin-top:2px}')
    H.append('.grd{flex:1;display:grid;grid-template-columns:45% 55%;overflow:hidden}')
    H.append('.lft{background:#f5f5f5;border-right:1px solid #ddd;overflow-y:auto;padding:10px}')
    H.append('.rgt{background:#fff;overflow-y:auto;padding:12px;color:#999;display:flex;align-items:center;justify-content:center;text-align:center}')
    H.append('.rgt.has-items{align-items:flex-start;justify-content:flex-start}')
    H.append('.dbtn{width:100%;padding:10px;background:#fff;border:1px solid #ddd;border-radius:6px;margin-bottom:5px;font-size:13px;cursor:pointer}')
    H.append('.dbtn.act{background:#1e5a96;color:#fff}')
    H.append('.lbtn{padding:10px 12px;background:#f0f0f0;border:1px solid #ddd;border-radius:4px;margin-bottom:6px;font-size:12px;cursor:pointer;display:block;width:100%}')
    H.append('.frm{padding:0;flex-direction:column;flex:1}')
    H.append('.frm-hd{background:linear-gradient(135deg,#1e5a96,#154a7a);color:#fff;padding:12px 16px}')
    H.append('.frm-hd-title{font-size:15px;font-weight:700}.frm-hd-sub{font-size:11px;opacity:.85;margin-top:3px}')
    H.append('.frm-body{padding:14px;overflow-y:auto;flex:1}.fg{margin-bottom:12px}')
    H.append('.fg-label{font-size:12px;font-weight:700;color:#333;margin-bottom:4px;display:block}.fg-hint{font-size:10px;color:#888;margin-bottom:6px}')
    H.append('select{width:100%;padding:9px;border:1px solid #ddd;border-radius:6px;font-size:13px;background:#fff}')
    H.append('textarea.notes{width:100%;padding:9px;border:1px solid #ddd;border-radius:6px;font-size:12px;min-height:72px;resize:none}')
    H.append('.sig-box{width:100%;height:120px;border:2px solid #1e5a96;border-radius:6px;background:#fff;cursor:crosshair;display:block}')
    H.append('.sig-btns{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:6px}')
    H.append('.sig-btn{padding:8px;border:1px solid #ddd;border-radius:6px;cursor:pointer;font-size:12px;background:#fff;font-weight:600}')
    H.append('input.ni{width:100%;padding:9px;border:1px solid #ddd;border-radius:6px;font-size:13px}')
    H.append('.ff{padding:10px 14px;border-top:1px solid #eee;display:grid;grid-template-columns:1fr 1fr;gap:8px;background:#fff}')
    H.append('.br{padding:11px;border:1px solid #ddd;border-radius:8px;cursor:pointer;font-size:13px;font-weight:600;background:#fff;color:#333}')
    H.append('.bs{padding:11px;border:none;border-radius:8px;cursor:pointer;font-size:13px;font-weight:600;background:#1e5a96;color:#fff}')
    H.append('</style></head>')
    H.append('<body><div id="p"><div class="n">9:41</div><div class="s"><span>&#x1F4F6;</span><span>&#x1F50B;</span></div>')
    H.append('<div class="pg lg sh"><div class="cd"><div class="ico">&#x1F3DB;&#xFE0F;</div>')
    H.append('<div class="nm">\uBA54\uD0C0\uB3C4\uC5B4</div><div class="sb">\uC720\uC9C0\uBCF4\uC218 \uC810\uAC80 \uC2DC\uC2A4\uD15C</div>')
    H.append('<label class="lbl">\uC544\uC774\uB514</label><input type="text" id="u" value="admin">')
    H.append('<label class="lbl">\uBE44\uBC00\uBC88\uD638</label><input type="password" id="pw" value="admin123">')
    H.append('<button class="bl" onclick="fn_login()">\uB85C\uADF8\uC778</button>')
    H.append('<div style="font-size:10px;color:#aaa;margin-top:10px">\uAD8C\uD55C\uC790\uAC00 \uB4F1\uB85D\uD55C<br>\uC9C1\uC6D0\uB9CC \uB85C\uADF8\uC778 \uAC00\uB2A5\uD569\uB2C8\uB2E4.</div>')
    H.append('</div></div>')
    H.append('<div class="pg slp"><div class="hd"><div class="hd-title">\uAC80\uACB0\uACFC \uC704\uCE58 \uC120\uD0DD</div><div class="hd-sub">2\uB2E8\uACC4 / 3\uB2E8\uACC4</div></div>')
    H.append('<div class="grd"><div class="lft" id="dl"></div><div class="rgt" id="rl">\uC120\uD0DD\uD558\uC138\uC694</div></div></div>')
    H.append('<div class="pg frm"><div class="frm-hd"><div class="frm-hd-title">\uC810\uAC80 \uD56D\uBAA9 \uC120\uD0DD</div><div class="frm-hd-sub" id="tt"></div></div>')
    H.append('<div class="frm-body">')
    H.append('<div class="fg"><label class="fg-label">\uC810\uAC80 \uD56D\uBAA9</label><select id="it"><option>-- \uD56D\uBAA9 \uC120\uD0DD --</option></select></div>')
    H.append('<div class="fg"><label class="fg-label">\uC870\uCE58 \uB0B4\uC6A9</label><div class="fg-hint">\uC774\uC0C1 \uBC1C\uACAC \uC2DC \uAE30\uB85D</div>')
    H.append('<textarea class="notes" id="ct" placeholder="\uC608: \uD328\uB110 \uBC88\uC778 \u2192 \uCD08\uAE30\uD654 \uC644\uB8CC"></textarea></div>')
    H.append('<div class="fg"><label class="fg-label">\uC11C\uBA85</label>')
    H.append('<canvas class="sig-box" id="sig" width="320" height="120"></canvas>')
    H.append('<div class="sig-btns"><button class="sig-btn" onclick="fn_sig_clear()">\uC9C0\uC6B0\uAE30</button>')
    H.append('<button class="sig-btn" style="color:#1e5a96" onclick="fn_sig_save()">\uC800\uC7A5</button></div></div>')
    H.append('<div class="fg"><label class="fg-label">\uC810\uAC80\uC790\uBA85</label>')
    H.append('<input class="ni" type="text" id="nm" placeholder="\uC810\uAC80\uC790\uBA85 \uC785\uB825"></div>')
    H.append('</div><div class="ff"><button class="br" onclick="fn_reset()">\uCD08\uAE30\uD654</button>')
    H.append('<button class="bs" onclick="fn_save()">\uC800\uC7A5 &#x2193;</button></div></div></div></div>')
    H.append('<script>')
    H.append('const IT='+IT+';')
    H.append('const LC='+LC+';')
    H.append('let pg=0,ds="",lo="",sigCanvas,sigCtx,drawing=false;')
    H.append('window.onload=function(){sigCanvas=document.getElementById("sig");sigCtx=sigCanvas.getContext("2d");sigCtx.strokeStyle="#222";sigCtx.lineWidth=2;sigCtx.lineCap="round";sigCanvas.addEventListener("mousedown",function(e){drawing=true;sigCtx.beginPath();sigCtx.moveTo(e.offsetX,e.offsetY)});sigCanvas.addEventListener("mousemove",function(e){if(!drawing)return;sigCtx.lineTo(e.offsetX,e.offsetY);sigCtx.stroke()});sigCanvas.addEventListener("mouseup",function(){drawing=false});};')
    H.append('function sh(n){pg=n;document.querySelectorAll(".pg").forEach(function(e){e.classList.remove("sh")});document.querySelectorAll(".pg")[n].classList.add("sh")}')
    H.append('function fn_login(){if(document.getElementById("u").value==="admin"&&document.getElementById("pw").value==="admin123"){ld();sh(1)}}')
    H.append('function ld(){var el=document.getElementById("dl");el.innerHTML="";Object.keys(LC).forEach(function(k){var b=document.createElement("button");b.className="dbtn";b.textContent=k;b.onclick=function(){sd(k,b)};el.appendChild(b)});}')
    H.append('function sd(k,b){document.querySelectorAll(".dbtn").forEach(function(e){e.classList.remove("act")});b.classList.add("act");ds=k;var rl=document.getElementById("rl");rl.className="rgt has-items";rl.innerHTML="";LC[k].forEach(function(v){var d=document.createElement("button");d.className="lbtn";d.textContent=v;d.onclick=function(){sl(v)};rl.appendChild(d)});}')
    H.append('function sl(v){lo=v;document.getElementById("tt").textContent=ds+" - "+v+" | 3\\ub2e8\\uacc4 / 3\\ub2e8\\uacc4";var s=document.getElementById("it");s.innerHTML="<option>-- \\ud56d\\ubaa9 \\uc120\\ud0dd --</option>";IT.forEach(function(j){var o=document.createElement("option");o.value=j;o.textContent=j;s.appendChild(o)});rf();sh(2);}')
    H.append('function rf(){document.getElementById("ct").value="";document.getElementById("nm").value="";if(sigCtx)sigCtx.clearRect(0,0,sigCanvas.width,sigCanvas.height);}')
    H.append('function fn_sig_clear(){if(sigCtx)sigCtx.clearRect(0,0,sigCanvas.width,sigCanvas.height);}')
    H.append('function fn_sig_save(){alert("\\uc11c\\uba85\\uc774 \\uc800\\uc7a5\\ub418\\uc5c8\\uc2b5\\ub2c8\\ub2e4.");}')
    H.append('function fn_reset(){document.getElementById("it").value="-- \\ud56d\\ubaa9 \\uc120\\ud0dd --";rf();}')
    H.append('function fn_save(){if(document.getElementById("it").value==="-- \\ud56d\\ubaa9 \\uc120\\ud0dd --"){alert("\\uc810\\uac80 \\ud56d\\ubaa9\\uc744 \\uc120\\ud0dd\\ud558\\uc138\\uc694");return;}alert("\\uc800\\uc7a5 \\uc644\\ub8cc!");sh(1);ld();}')
    H.append('</script></body></html>')
    return ''.join(H)

if __name__=='__main__':
    app.run(host='0.0.0.0',port=int(os.environ.get('PORT',8080)),debug=False)
